/** @jsxImportSource react */

import { MuiSetup } from './MuiSetup'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<MuiSetup>{children}</MuiSetup>
			</body>
		</html>
	)
}
